#!/usr/bin/env bash
# AudyNesia
# Copyright © 2021, AudyNesia
# All rights reserved
#


_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "AudyNesia" ]]
    then
        echo "WVVoU01HTklUVFpNZVRsdVlWaFNiMlJYU1hWWk1qbDBUREpvY0dSSE9YSmhXSEEyWlZNNVFtUlhValZVYlZaNllWZEZkbGxZU21waFIyd3lXbE01ZEZsWVRqQmFXRWwxWlcxc2R3PT0=" | base64 -d
    elif [[ $UPSTREAM_REPO == "AudyNesia" ]]
    then
        echo "WVVoU01HTklUVFpNZVRsdVlWaFNiMlJYU1hWWk1qbDBUREpvY0dSSE9YSmhXSEEyWlZNNVFtUlhValZVYlZaNllWZEZkbGxZU21waFIyd3lXbE01ZEZsWVRqQmFXRWwxWlcxc2R3PT0=" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "WVVoU01HTklUVFpNZVRsdVlWaFNiMlJYU1hWWk1qbDBUREpvY0dSSE9YSmhXSEEyWlZNNVFtUlhValZVYlZaNllWZEZkbGxZU21waFIyd3lXbE01ZEZsWVRqQmFXRWwxWlcxc2R3PT0=" | base64 -d
    fi
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "AudyNesia" ]]
    then
        rlink=`echo "WVVoU01HTklUVFpNZVRsdVlWaFNiMlJYU1hWWk1qbDBUREpvY0dSSE9YSmhXSEEyWlZNNVFtUlhValZVYlZaNllWZEZkbGxZU21waFIyd3lXbE01ZEZsWVRqQmFXRWwxWlcxc2R3PT0=" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        rlink=`echo "${UPSTREAM_REPO}"`
    else
        rlink=`echo "WVVoU01HTklUVFpNZVRsdVlWaFNiMlJYU1hWWk1qbDBUREpvY0dSSE9YSmhXSEEyWlZNNVFtUlhValZVYlZaNllWZEZkbGxZU21waFIyd3lXbE01ZEZsWVRqQmFXRWwxWlcxc2R3PT0=" | base64 -d`
    fi
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_AudyNesia_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/AudyNesia51/AudyNesia"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_cod_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath
    zippath="AudyNesia.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_ziplink) -O "$zippath"
    echo "  Unpacking Data ..."
    CODPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    _run_AudyNesia_git
    cd $CODPATH
    _run_cod_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "   ❦ Starting AudyNesia Userbot ❦   "
    echo "
    
      ░█████╗░██╗░░░██╗██████╗░██╗░░░██╗███╗░░██╗███████╗░██████╗██╗░█████╗░
      ██╔══██╗██║░░░██║██╔══██╗╚██╗░██╔╝████╗░██║██╔════╝██╔════╝██║██╔══██╗
      ███████║██║░░░██║██║░░██║░╚████╔╝░██╔██╗██║█████╗░░╚█████╗░██║███████║
      ██╔══██║██║░░░██║██║░░██║░░╚██╔╝░░██║╚████║██╔══╝░░░╚═══██╗██║██╔══██║
      ██║░░██║╚██████╔╝██████╔╝░░░██║░░░██║░╚███║███████╗██████╔╝██║██║░░██║
      ╚═╝░░╚═╝░╚═════╝░╚═════╝░░░░╚═╝░░░╚═╝░░╚══╝╚══════╝╚═════╝░╚═╝╚═╝░░╚═╝
    "
    echo "

           ██╗░░░██╗░██████╗███████╗██████╗░██████╗░░█████╗░████████╗
           ██║░░░██║██╔════╝██╔════╝██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝
           ██║░░░██║╚█████╗░█████╗░░██████╔╝██████╦╝██║░░██║░░░██║░░░
           ██║░░░██║░╚═══██╗██╔══╝░░██╔══██╗██╔══██╗██║░░██║░░░██║░░░
           ╚██████╔╝██████╔╝███████╗██║░░██║██████╦╝╚█████╔╝░░░██║░░░
           ░╚═════╝░╚═════╝░╚══════╝╚═╝░░╚═╝╚═════╝░░╚════╝░░░░╚═╝░░░
    "
    python3 -m AudyNesia & python3 main.py
}

_set_bot
